test_lab1:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - val runner docker executor
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab1 | tee output.log
    - python3 upload.py

test_lab2:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - val runner docker executor
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab2 | tee output.log
    - python3 upload.py

test_lab3:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - val runner docker executor
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab3 | tee output.log
    - python3 upload.py

test_lab4:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - val runner docker executor
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab4 | tee output.log
    - python3 upload.py

test_lab5_part1:
 image: ipadsse302/tigerlabs_score_env
 tags:
   - val runner docker executor
 stage: test
 script:
   - rm -rf scripts testdata
   - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
   - make gradelab5-1 | tee output.log
   - python3 upload.py

test_lab5:
 image: ipadsse302/tigerlabs_score_env
 tags:
   - val runner docker executor
 stage: test
 script:
   - rm -rf scripts testdata
   - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
   - make gradelab5 | tee output.log
   - python3 upload.py

# test_lab6:
#  image: ipadsse302/tigerlabs_score_env
#  tags:
#    - val runner docker executor
#  stage: test
#  script:
#    - rm -rf scripts testdata
#    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
#    - make gradelab6 | tee output.log
#    - python3 upload.py
#
# test_all:
#   image: ipadsse302/tigerlabs_score_env
#   tags:
#     - val runner docker executor
#   stage: test
#   script:
#     - rm -rf scripts testdata
#     - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
#     - make gradeall | tee output.log
#     - python3 upload.py
# 
